project_id = "epcgshxoajvqwgrmwduv"

[db]
# Database configuration
shadow_port = 54329

[api]
enabled = true
port = 54321

[db.pooler]
enabled = false

# Development-specific configuration (rename from "staging")
[remotes.development]
project_id = "dgrnuytifkjzlkpgtjzo"

[remotes.development.api]
max_rows = 1000

# Production-specific configuration
[remotes.production]
project_id = "epcgshxoajvqwgrmwduv"  # <-- ensure this is the prod ref

[remotes.production.api]
max_rows = 1000